spring.application.name=projectOne
spring.datasource.url=jdbc:postgresql://localhost:5432/projectOne
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect